server:
  port: 9000

spring:
  application:
    name: geekup
  datasource:
    url: jdbc:postgresql://localhost:5433/ecommerce
    username: ecommerce_user
    password: ecommerce_pass
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false

logging:
  level:
    liquibase: DEBUG
